id: fhir.example
canonical: http://example.org
name: largeIG
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ci-build
publisher:
  name: Example Publisher
  url: http://example.org/example-publisher

parameters:
  validation:
    - allow-any-extensions
  no-validate:
    - CodeSystem/*
    - ValueSet/*
  i18n-default-lang: en
  i18n-lang: 
  - fr
  - de 
  - pt
  - es
  - lt




menu:
  Home: index.html
  Artifacts: artifacts.html

instanceOptions:
  manualSliceOrdering: true